# Generated by Django 5.0.2 on 2024-02-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PricingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distance_base_price",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "distance_additional_price",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "time_multiplier_factor",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "waiting_charges",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Tue-Wed-Thur", "Tue, Wed, Thur"),
                            ("Sat-Mon", "Sat, Mon"),
                            ("Sun", "Sun"),
                        ],
                        max_length=20,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
